services:
  - redis
  - docker
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
language: python
dist: focal
jobs:
  include:
    - python: "3.8"
      env: TOX_ENV=py38-sentry22
install:
  - sudo apt update
  - sudo apt install libnss3-dev libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config -y
  - docker network create -d bridge sentry_test
  - docker run -p 8123:8123 -p 9000:9000 -p 9009:9009 --network sentry_test -d --name
    sentry_clickhouse yandex/clickhouse-server:20.8.19.4
  - docker run -p 1218:1218 -d -e SNUBA_SETTINGS=docker -e DEBUG=1 -e CLICKHOUSE_HOST=sentry_clickhouse
    --network sentry_test --name sentry_snuba getsentry/snuba:22.8.0 devserver --no-workers
  - docker ps -a
  - docker logs sentry_snuba
  - travis_retry pip install tox
before_script:
  - psql -c 'create database sentry;' -U postgres
script: tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: LB8jdjwO1kplAVtgoDUcnO/w50wxd0eA2SgJThNmm1NElnIPjuThDRLU3VI0b72ua9IRbMiLft9wNi//apiBdgriP+rmRVpIjdj2jPiroyM7PiZfPBw07z7Xj/xKAaPDZ/jEjpBBO27nnoxQ61/aVdzSHctYyhe/+wcSngcgDTDC5BF7zDXL0fVsju+ZanHkJ/WUrf/t6ySPteV4nsvYmoq3EWs6Ua+CyKZxa6nhqJJB5NkhTSMdngVfOLTjqvC2WeMAvzDNMPZ+b3Tb5R7ssYsrPkTB0f0IxZ81QfU3FDmaCN0k5moZQjvQsX0w2pAceBH0lRLbib9z/+XNv9rimuFs/6VBCFSISzPz2PjzEaS53RQ6TOF4iNTf3HXUk5/om3qm5juLxoh9vm393RmUoAFBbWsliWmqKweBMBoamSxrYm2+f+1yYYL2nS4sdHnmuWKNDyao/9wyZWHib9kdYprcen8TzY9V67vQCSa9xEwF/El6YUhlDS2Td2nJqhKCmMkwJtIB7cWFT+xQcITBNoMMmA7iXshnz175W8g+qD/hqAZbjrxhZAtJkRRURACyz3LeDvuOF5WAcnA6Z4VDlDdfHJozJ/UnilKboVHBkjH7Lk6RUcZXh5n54T4T2wVHdJJ+48LmAD2D2D89vMG7lSUTeXD2DEFSEPW5mMyx0fg=
  skip_existing: true
  on:
    tags: true
  distributions: sdist bdist_wheel
