services:
  - redis
  - docker
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
language: python
dist: focal
jobs:
  include:
    - python: "3.8"
      env: TOX_ENV=py38-sentry22
install:
  - sudo apt update
  - sudo apt install libnss3-dev libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config -y
  - docker network create -d bridge sentry_test
  - docker run -p 8123:8123 -p 9000:9000 -p 9009:9009 --network sentry_test -d --name
    sentry_clickhouse yandex/clickhouse-server:20.8.19.4
  - docker run -p 1218:1218 -d -e SNUBA_SETTINGS=docker -e DEBUG=1 -e CLICKHOUSE_HOST=sentry_clickhouse
    --network sentry_test --name sentry_snuba getsentry/snuba:22.8.0 devserver --no-workers
  - docker ps -a
  - docker logs sentry_snuba
  - travis_retry pip install tox
before_script:
  - psql -c 'create database sentry;' -U postgres
script: tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "PrZ1Mz5okwFCK0DWJthM8PmajH8cg6NbRARAt48CfiVg0jEvaAPZbwQzxLaHhwJ4yWTztsFu33wPIzsI1PWm0HHmkgLyBaUwXlUIwzkTGrWRQ0EA4Vyv7hv9ytQwPl2bhP5Qmx4lWCZnJJdnpGZX9iDFvffWEh/jCuuoMG2+LpWH2vWGpofd/XgzqYQa2dM6ZK6FlXpdz74tA6HFsFJ1p9cVrFZ9+2qLZ9ENU9cagzofAlPuYaDqWYljw4szCIghCpvKR9AO/oCkWDEbY823VzKOkgTKP21Wj2OP3JMyK5wd7+hV6cLQtKTYTFddMP2dIi99C2EI01wSioRbbH8vWnbyNIkFjAOb5Ghh/p3J6SeSFCVuzC56to3prhFoeYR2Ta3XF0R+pwvW48SguRTUzKkPONTuUvwFHF1aTMI/fLcmQVEiAZx0gvPems+aU7w0A/vwCHfP/OHd1pVXdjxrQ26sNNBh69pBRhaKAdh3sYApK+SVapjw85NStpSvkRryMZBBdUuhWU/xbZSGQDg3C1zNnWHdrD0dQUNT04wD4iCXcWUYYcWTNHURQrzcb5nDnBYKJ9Wo0ZSIhgCG3K+ootC9etyh59UJ2AO1GdfiUc0locuphdr7aCONQT+ZKBMABX8N23Id9U3yxEq0D/8mQbf819DnDWoo9P/2YWSoLSE="
  skip_existing: true
  on:
    tags: true
  distributions: sdist bdist_wheel
